### PR TITLE
Add an event display for npz files with endcaps data

### PR DESCRIPTION
**Pull request by ABlairJamieson**

### CODE REVIEW

**Review by pdeperio — CHANGES_REQUESTED** [review]
Possible to implement white background option? (The black tends not to be very visible in slide presentations.)

**Comment by ABlairJamieson** [comment]
I updated the display to use white by default.  Apparently adding _r to the end of the colourmap name reverses the order of the colours.  Also fixed a few bugs.  I found a difficult bug that seems to indicate the PMT numbers are 1:NPMTs in the geometry file, but 0:NPMTs-1 in the event files.

**Review by pdeperio — APPROVED** [review]

**Comment by nickwp** [comment]
> I found a difficult bug that seems to indicate the PMT numbers are 1:NPMTs in the geometry file, but 0:NPMTs-1 in the event files.

Yes, this comes from how WCSim itself stores the PMT IDs. In some cases they are zero-index and in other cases they're 1-indexed. In the geometry file it's directly copied from the WCSim root file. When creating the new npz format files it subtracts 1 to make sure that they are zero-indexed, because that's required to be compatible with the conversion script the capstone students used and with the functions in `pos_utils.py`. Are you using those functions to get rows/columns from PMT ID and seeing issues there, or not using them? (or similarly for the csv file the capstone students made, if you're using that instead)
Actually, I thought that in the geometry file it would also be 0-indexed because when dealing with WCSim root files, you usually need to subtract 1 from the PMT IDs to get the correct PMT from the geometry tree (e.g. see [here](https://github.com/nuPRISM/WCSim/blob/nuPRISM/develop/sample-root-scripts/sample_readfile.C#L210)) but you're saying that the geometry file has PMTs 1-indexed?

**Comment by nickwp** [comment]
I just checked WCSim code, and it seems that PMT IDs are stored as 1-indexed in the geometry tree, but the `GetPMT(i)` function doesn't get the PMT with ID `i` but instead gets the PMT at position `i` in the TClonesArray which is the PMT with ID `i+1`. So I think this notebook is now fine. I could update geometry dump script indexing to make things consistent at least on the watchmal side, and if I do then I'll update this notebook too (I don't think anything else is using both those files together, apart from my pointnet code, that I'll also update).

**Pull request merged**
